# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /calculator

# Copy the current directory contents into the container at /app
COPY . /calculator

# Run the command to start the application
CMD ["python", "calculator.py"]
